Areas/Admin/Controllers/ProductTypeController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShope.Data;
using OnlineShope.Models;
using System.Drawing.Text;
using static System.Collections.Specialized.BitVector32;

namespace OnlineShope.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductTypeController : Controller
    {
        private ApplicationDbContext _db;
        public ProductTypeController(ApplicationDbContext db) 
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View(_db.ProductTypes.ToList());
        }

        // Create Get Action Method
        public ActionResult Create() 
        {
            return View();
        }

        // Create Post Action Method

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductType productType)
        {
            if (ModelState.IsValid)
            {
                var searchProdutType = _db.ProductTypes.FirstOrDefault(c => c.ProductTypes==productType.ProductTypes);
                if(searchProdutType != null)
                {
                    ViewBag.message = "ProductType already Exist";
                    return View(productType);
                }
                _db.ProductTypes.Add(productType);  
                await _db.SaveChangesAsync();
                TempData["save"] = "Product Add Succesfully";
                return RedirectToAction("Index");
            }
            return View(productType);
        }

        // Edit Get Action Method
        public ActionResult Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var producttype = _db.ProductTypes.Find(id);
            if (producttype == null)
            {
                return NotFound();
            }
            return View(producttype);
        }

        // Edit Post Action Method

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductType productType)
        {
            if (ModelState.IsValid)
            {
                var searchProdutType = _db.ProductTypes.FirstOrDefault(c => c.ProductTypes == productType.ProductTypes);
                if (searchProdutType != null)
                {
                    ViewBag.message = "ProductType already Exist";
                    return View(productType);
                }
                _db.Update(productType);
                await _db.SaveChangesAsync();
                TempData["update"] = "Product Update Succesfully";
                return RedirectToAction("Index");

            }
            return View(productType);
        }

        // Details Get Action Method
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producttype = _db.ProductTypes.Find(id);
            if (producttype == null)
            {
                return NotFound();
            }
            return View(producttype);
        }

        // Details Post Action Method

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Details(ProductType productType)
        {
            return View(productType);
        }


        // Delete Get Action Method
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producttype = _db.ProductTypes.Find(id);
            if (producttype == null)
            {
                return NotFound();
            }
            return View(producttype);
        }

        // Delete Post Action Method

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete( int? id, ProductType productType)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (productType == null)
            {
                return NotFound();
            }
            if(id != productType.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Remove(productType);
                await _db.SaveChangesAsync();
                TempData["delete"] = "Product Delete Succesfully";
                return RedirectToAction("Index");
            }
            return View(productType);
        }

    }
}

Areas/Admin/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineShope.Data;
using OnlineShope.Models;
using Microsoft.AspNetCore.Hosting;
using System.Linq;

namespace OnlineShope.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductsController : Controller
    {
        private ApplicationDbContext _db; 

        private IWebHostEnvironment _he;
        public ProductsController(ApplicationDbContext db, IWebHostEnvironment he)
        {
            _db = db; 
            _he = he;
        }

        public IActionResult Index()
        {
            return View(_db.Pruducts.Include(c=>c.SpacialTag).Include(c=>c.productType).ToList());
        }
        //Get  Action Method
        public IActionResult Create()
        {
            ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(),"Id", "ProductTypes");
            ViewData["SpacialTagId"] = new SelectList(_db.SpacialTags.ToList(), "Id", "Condition");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Products products, IFormFile? Image)
        {
            if(ModelState.IsValid)
            {
                var searchProduct = _db.Pruducts.FirstOrDefault(c => c.Name == products.Name);
                if(searchProduct != null)
                {
                    ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductTypes");
                    ViewData["SpacialTagId"] = new SelectList(_db.SpacialTags.ToList(), "Id", "Condition");
                    ViewBag.message = "This Product already Exist";
                    return View(products);
                }
                if(Image != null)
                {
                    var name = Path.Combine(_he.WebRootPath+ "/Upload", Path.GetFileName(Image.FileName));
                    await Image.CopyToAsync(new FileStream(name, FileMode.Create));
                    products.Img = "Upload/" + Image.FileName;
                }
                _db.Pruducts.Add(products);
                await _db.SaveChangesAsync();
                TempData["Save"] = "Product Add Succesfully";
                return RedirectToAction("Index");
            }
            return View(products);

        }

        //Get Action Method
        public IActionResult Edit(int? id)
        {
            ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductTypes");
            ViewData["SpacialTagId"] = new SelectList(_db.SpacialTags.ToList(), "Id", "Condition");
            if(id == null)
            {
                return NotFound();
            }
            var products = _db.Pruducts.Include(c => c.SpacialTag).Include(c=>c.productType).FirstOrDefault(c=> c.Id==id);
            if(products == null)
            {
                return NotFound();
            }
            return View(products);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Products products, IFormFile? Image)
        {
            if (ModelState.IsValid)
            {
                var searchProduct = _db.Pruducts.FirstOrDefault(c => c.Name == products.Name && c.Id != products.Id); //c.Id != products.Id this means when i check Product name mach or not but this Product id not check 
                if (searchProduct != null)
                {
                    ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductTypes");
                    ViewData["SpacialTagId"] = new SelectList(_db.SpacialTags.ToList(), "Id", "Condition");
                    ViewBag.message = "This Product already Exist";
                    return View(products);
                }
                if (Image != null)
                {
                    var name = Path.Combine(_he.WebRootPath + "/Upload", Path.GetFileName(Image.FileName));
                    await Image.CopyToAsync(new FileStream(name, FileMode.Create));
                    products.Img = "Upload/" + Image.FileName;
                }
                _db.Pruducts.Update(products);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(products);

        }

        //Get Action Method for View
        public IActionResult Details(int? id)
        {
            ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductTypes");
            ViewData["SpacialTagId"] = new SelectList(_db.SpacialTags.ToList(), "Id", "Condition");
            if (id == null)
            {
                return NotFound();
            }
            var products = _db.Pruducts.Include(c => c.SpacialTag).Include(c => c.productType).FirstOrDefault(c => c.Id == id);
            if (products == null)
            {
                return NotFound();
            }
            return View(products);
        }

        //Get Action Method For Delete
        public IActionResult Delete(int? id)
        {
            ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductTypes");
            ViewData["SpacialTagId"] = new SelectList(_db.SpacialTags.ToList(), "Id", "Condition");
            if (id == null)
            {
                return NotFound();
            }
            var products = _db.Pruducts.Include(c => c.SpacialTag).Include(c => c.productType).FirstOrDefault(c => c.Id == id);
            if (products == null)
            {
                return NotFound();
            }
            return View(products);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Products products, int? id)
        {
            if (ModelState.IsValid)
            {
                if(id== null)
                {
                    return NotFound();
                }
                if(products== null)
                {
                    return NotFound();
                }
                if(id != products.Id)
                {
                    return NotFound();
                }
                _db.Pruducts.Remove(products);
                await _db.SaveChangesAsync();
                TempData["Delete"] = "Product Deleted";
                return RedirectToAction("Index");
            }
            return View(products);

        }
        //Filtering Product with Price
        //Using Post Action Mathod
        [HttpPost]
        public IActionResult Index(decimal? lowPrice, decimal? highPrice)
        {
            var products = _db.Pruducts.Include(c => c.productType).Include(c => c.SpacialTag).Where(c => c.Price >= lowPrice && c.Price <= highPrice).ToList();
            if(lowPrice == null || highPrice == null)
            {
                products = _db.Pruducts.Include(c => c.productType).Include(c => c.SpacialTag).ToList();
                
            }
            if (products.Count == 0)
            {
                TempData["Message"] = "No products found.";
            }
            return View(products);
        }
    }
}

Areas/Admin/Controllers/SpacialTagController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShope.Data;
using OnlineShope.Models;

namespace OnlineShope.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SpacialTagController : Controller
    {
        private ApplicationDbContext _db;
        public SpacialTagController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.SpacialTags.ToList());
        }

        // Create Get Action Method
        public ActionResult Create()
        {
            return View();
        }

        // Create Post Action Method

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SpacialTag spacialTag)
        {
            if (ModelState.IsValid)
            {
                
                _db.SpacialTags.Add(spacialTag);
                await _db.SaveChangesAsync();
                TempData["save"] = "Product Add Succesfully";
                return RedirectToAction("Index");
            }
            return View(spacialTag);
        }
    }
}

Views/Shared/_ButtonForProductPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model int
@{

}
<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Details" asp-controller="Products" class="btn btn-primary" asp-route-id="@Model"><i class="fa-solid fa-bars"></i></a>
        <a asp-action="Edit" asp-controller="Products" class="btn btn-success" asp-route-id="@Model"><i class="fa-regular fa-pen-to-square"></i></a>
        <a asp-action="Delete" asp-controller="Products" class="btn btn-danger" asp-route-id="@Model"><i class="fa-solid fa-trash"></i></a>
    </div>
</td>

Views/Shared/_ButtonPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model int
@{

}
<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Details" asp-controller="ProductType" class="btn btn-primary" asp-route-id="@Model"><i class="fa-solid fa-bars"></i></a>
        <a asp-action="Edit" asp-controller="ProductType" class="btn btn-success" asp-route-id="@Model"><i class="fa-regular fa-pen-to-square"></i></a>
        <a asp-action="Delete" asp-controller="ProductType" class="btn btn-danger" asp-route-id="@Model"><i class="fa-solid fa-trash"></i></a>
    </div>
</td>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineShope</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.1/css/buttons.dataTables.min.css" />
    <link rel="stylesheet" href="~/OnlineShope.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineShope</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductType" asp-action="Index">Product List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="SpacialTag" asp-action="Index">Spacial Tag</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OnlineShope - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.print.min.js"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>